/////////////////////////////////////////////////////////////////////////////
// CATCH SETTINGS ///////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////
module.exports = {
  CONFIG_CATCHES_STATS_LIST: [
    "Catch & Release", 
    "Meatfish",
    // "Flyfish",
    // "Bass"
  ],
  CONFIG_CATCHES_SPECIES_LIST: [
    {
      label: "Blue Marlin",
      category: "Catch & Release",
      points: 300,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      label: "White Marlin",
      category: "Catch & Release",
      points: 150,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      label: "Spearfish",
      category: "Catch & Release",
      points: 150,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      label: "Sailfish",
      category: "Catch & Release",
      points: 100,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      label: "Dorado",
      category: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    { 
      label: "Tuna", 
      category: "Meatfish", 
      points: 1, 
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    { 
      label: "Wahoo", 
      category: "Meatfish", 
      points: 1, 
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    // { 
    //   label: "Redfish", 
    //   category: "Flyfish", 
    //   points: 1, 
    //   pointsCalculationMethod: "lengthExact",
    //   weightIsRequired: true,
    //   lengthIsRequired: true,
    //   girthIsRequired: true,
    //   dateTimeIsRequired: true,
    //   photoIsRequired: true,
    // },
    // { 
    //   label: "Largemouth Bass", 
    //   category: "Bass", 
    //   points: 1, 
    //   pointsCalculationMethod: "lengthRoundUp",
    //   weightIsRequired: true,
    //   lengthIsRequired: true,
    //   girthIsRequired: true,
    //   dateTimeIsRequired: true,
    //   photoIsRequired: false,
    // },
  ],
};

